data:
  name: 'SWE_Nonlinear-0000'
  total_num: 50
  n_train: 45
  n_test: 5
  nx: 128
  nt: 100
  sub: 1
  sub_t: 1
  nin: 1
  nout: 3
  g: 1.0
  H: 1.0
  nu: 0.002

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  in_dim: 4
  out_dim: 3
  activation: 'gelu'
  padding: 5

train:
  batchsize: 1
  # epochs: 500
  # milestones: [150, 250, 350, 450, 550, 650, 750, 850, 950]
  # milestones: [150, 300, 450]
  epochs: 150
  milestones: [25, 50, 75, 100, 125, 150]
  # milestones: [50, 100, 150]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 10.0
  h_loss: 1.0
  u_loss: 1.0
  v_loss: 1.0
  save_dir: 'SWE_Nonlinear'
  save_name: 'SWE_Nonlinear-0000.pt'
  ckpt: 'checkpoints/SWE_Nonlinear/SWE_Nonlinear-0000.pt'
  ckpt_freq: 25

log:
  project: 'PINO-SWE_Nonlinear'
  group: 'SWE_Nonlinear-0000'

test:
  batchsize: 1
  ckpt: 'checkpoints/SWE_Nonlinear/SWE_Nonlinear-0000.pt'
